
title: Snappy Apps Development
email: snappyappsdev@gmail.com
description: "Snappy Apps Development was created to showcase a systematic
approach to creating an Android App."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://snappyappsdev.github.io/"
github_username:  snappyappsdev

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

permalink: none

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Leonardo Rocha"
      category: "Nonverbal-Communicator-App"
