- icon: "icon ion-coffee"
  title: "Java"
  content: "I plan on furthering my Java development skills."

- icon: "ion-social-android"
  title: "App Design"
  content: "I am almost done with my first Android App protoype"
